apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: email-service
  template:
    metadata:
      labels:
        component: email-service
    spec:
      containers:
        - name: email-service
          image: faustaleonardo/medanstore-email-service
          ports:
            - containerPort: 5007
          env:
            - name: EMAIL_HOST
              value: smtp.mailtrap.io
            - name: EMAIL_PORT
              value: '2525'
            - name: EMAIL_USERNAME
              value: 781934d785048c
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emailpassword
                  key: EMAIL_PASSWORD
            - name: SENDGRID_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sendgridpassword
                  key: SENDGRID_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwtsecretkey
                  key: JWT_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: email-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: email-service
  ports:
    - port: 5007
      targetPort: 5007
