apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: order-service
  template:
    metadata:
      labels:
        component: order-service
    spec:
      containers:
        - name: order-service
          image: faustaleonardo/medanstore-order-service
          ports:
            - containerPort: 5005
          env:
            - name: PG_USERNAME
              value: postgres
            - name: PG_HOST
              value: db-instance-pg-medanhost.c5z41jrlcefd.ap-southeast-1.rds.amazonaws.com
            - name: PG_PORT
              value: '5432'
            - name: PG_DATABASE
              value: medanstore_microservice_orders
            - name: DIALECT
              value: postgres
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwtsecretkey
                  key: JWT_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: order-service
  ports:
    - port: 5005
      targetPort: 5005
